[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "A4MVGRP4ycfRTe8kHuD6bB6vfEG2vu984V9KGzKqMDHo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/kali/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
